variable "name" {
  description = "(Required) The name of the provider to create."
  type        = string
}

variable "saml_metadata_document" {
  description = "(Required) An XML document generated by an identity provider that supports SAML 2.0."
  type        = string
}